### ISSUE TITLE
Extensão de templates

### ISSUE THREAD

**Issue by yamadapc** [beijaflor-io/jats2tex#27]
Mudar o formato de templates para suportar extensão de templates existentes.

**Comment by yamadapc** [comment]
```yaml
version: '1'
extends: 'nome-de-template-no-diretorio-de-configuracao ou path ou URL'
rules:
  tag1: ...
  tag2: ...
```
